language: rust
rust:
  - nightly
services:
  - postgresql

before_install:
  - psql -c 'DROP DATABASE IF EXISTS GameServiceTest;' -U postgres
  - psql -c 'CREATE DATABASE GameServiceTest;' -U postgres

script:
  - cargo build --verbose
  - cargo test --verbose
