language: rust
rust:
  - nightly
cache: cargo
services:
  - postgresql

before_install:
  - psql -c 'DROP DATABASE IF EXISTS GameServiceTest;' -U postgres
  - psql -c 'CREATE DATABASE GameServiceTest;' -U postgres
  - psql -c 'DROP TABLE IF EXISTS __diesel_schema_migrations;' -U postgres

script:
  - cargo build --verbose
  - cargo test --no-default-features --verbose
