language: rust
rust:
  - nightly
services:
  - postgresql

before_install:
  - psql -c 'DROP DATABASE IF EXISTS GameServiceTest;' -U postgres
  - psql -c 'CREATE DATABASE GameServiceTest;' -U postgres
  - psql -c 'DROP TABLE IF EXISTS __diesel_schema_migrations;' -U postgres
  - cargo install diesel_cli --no-default-features --features "postgres"
  - diesel migration run

script:
  - cargo build --verbose
  - cargo test --verbose
