[package]
authors = ["Fuzen-py <fuzen@protonmail.com>"]
name = "games-microservice"
version = "0.1.0"

[dependencies]
rand = "0.3.16"
rocket = "0.3.2"
rocket_codegen = "0.3.2"
serde = "1.0.14"
serde_derive = "1.0.14"
serde_json = "1.0.3"

[dependencies.rocket_contrib]
default-features = false
features = ["json"]
version = "0.3.2"
