[package]
authors = ["Fuzen-py <fuzen@protonmail.com>"]
name = "games-microservice"
version = "0.3.5"

[dependencies]
dotenv = "0.10.1"
r2d2 = "0.7.4"
r2d2-diesel = "0.16.0"
rand = "0.3.16"
serde = "1.0.15"
serde_derive = "1.0.15"
serde_json = "1.0.3"

[dependencies.diesel]
features = ["postgres"]
version = "0.16.0"

[dependencies.diesel_codegen]
features = ["postgres"]
version = "0.16.0"

[dependencies.rocket]
optional = true
version = "0.3.2"

[dependencies.rocket_codegen]
optional = true
version = "0.3.2"

[dependencies.rocket_contrib]
default-features = false
features = ["json"]
version = "0.3.2"

[features]
default = ["web"]
web = [
    "rocket",
    "rocket_codegen",
]

[[bin]]
required-features = ["web"]
name="game-service"
path="src/bin/game-service.rs"
