[package]
authors = ["Fuzen-py <fuzen@protonmail.com>"]
name = "games-microservice"
version = "0.5.0"

[[bin]]
name = "game-service"
path = "bin/main.rs"
required-features = [
    "web",
    "auto_save",
]

[dependencies]
cfg-if = "0.1.2"
cute = "0.3.0"
dotenv = "0.10.1"
lazy_static = "1.0.0"
log = "0.3.8"
rand = "0.4.1"
regex = "0.2.3"
serde = "1.0.24"
serde_derive = "1.0.24"
serde_json = "1.0.8"

[dependencies.diesel]
features = ["postgres"]
optional = true
version = "0.99.0"

[dependencies.diesel_migrations]
features = ["postgres"]
optional = true
version = "0.99.0"

[dependencies.r2d2]
optional = true
version = "0.8.1"

[dependencies.r2d2-diesel]
optional = true
version = "0.99.0"

[dependencies.rocket]
optional = true
version = "0.3.5"

[dependencies.rocket_codegen]
optional = true
version = "0.3.5"

[dependencies.rocket_contrib]
default-features = false
features = ["json"]
optional = true
version = "0.3.5"

[features]
auto_save = [
    "r2d2",
    "r2d2-diesel",
    "diesel",
    "diesel_migrations",
]
default = [
    "web",
    "auto_save",
]
web = [
    "rocket",
    "rocket_codegen",
    "rocket_contrib",
]
