[package]
authors = ["Fuzen-py <fuzen@protonmail.com>"]
name = "games-microservice"
version = "0.4.1"

[[bin]]
name = "game-service"
path = "src/bin/game-service.rs"
required-features = ["web"]

[dependencies]
cfg-if = "0.1.2"
cute = "0.3.0"
dotenv = "0.10.1"
lazy_static = "0.2.9"
r2d2 = "0.7.4"
r2d2-diesel = "0.16.0"
rand = "0.3.17"
regex = "0.2.2"
serde = "1.0.15"
serde_derive = "1.0.15"
serde_json = "1.0.3"

[dependencies.diesel]
features = ["postgres"]
version = "0.16.0"

[dependencies.diesel_codegen]
features = ["postgres"]
version = "0.16.0"

[dependencies.rocket]
optional = true
version = "0.3.3"

[dependencies.rocket_codegen]
optional = true
version = "0.3.3"

[dependencies.rocket_contrib]
default-features = false
features = ["json"]
optional = true
version = "0.3.3"

[features]
default = ["web"]
web = [
    "rocket",
    "rocket_codegen",
    "rocket_contrib",
]
