[package]
authors = ["Fuzen-py <fuzen@protonmail.com>"]
name = "games-microservice"
version = "0.4.2"

[[bin]]
name = "game-service"
path = "bin/main.rs"
required-features = ["web"]

[dependencies]
cfg-if = "0.1.2"
cute = "0.3.0"
dotenv = "0.10.1"
lazy_static = "1.0.0"
r2d2 = "0.8.1"
r2d2-diesel = "0.99.0"
rand = "0.3.18"
regex = "0.2.3"
serde = "1.0.23"
serde_derive = "1.0.23"
serde_json = "1.0.7"

[dependencies.diesel]
features = ["postgres"]
version = "0.99.0"

[dependencies.diesel_migrations]
features = ["postgres"]
version = "0.99.0"

[dependencies.rocket]
optional = true
version = "0.3.3"

[dependencies.rocket_codegen]
optional = true
version = "0.3.3"

[dependencies.rocket_contrib]
default-features = false
features = ["json"]
optional = true
version = "0.3.3"

[features]
default = ["web"]
web = [
    "rocket",
    "rocket_codegen",
    "rocket_contrib",
]
